In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
transactions = pd.read_csv("transactions_100k.csv")
customers = pd.read_csv("customers.csv")

print("Transactions Shape:", transactions.shape)
print("Customers Shape:", customers.shape)

Transactions Shape: (100000, 34)
Customers Shape: (10000, 12)

In [4]:
print("TRANSACTIONS")
display(transactions.head())

print("\nCUSTOMERS")
display(customers.head())

TRANSACTIONS

,Transaction_ID,Transaction_Timestamp,Transaction_Date,Transaction_Time,Customer_ID,Account_ID,Merchant_ID,Payment_Method,Transaction_Type,Amount,Transaction_Status,Device_Type,Device_ID,Location,State,IP_Address,Network_Type,Transaction_Channel,Previous_Transaction_Time,Time_Since_Last_Transaction_Min,Velocity_10Min_Count,Customer_Avg_Amount,Amount_Deviation_Pct,New_Device_Flag,Location_Mismatch_Flag,Geo_Distance_KM,Unusual_Hour_Flag,IP_Mismatch_Flag,Failed_Burst_Flag,Merchant_Risk_Flag,Fraud_Flag,Fraud_Reason,Risk_Score,Risk_Level
0,TXN00062954,2021-01-01 00:19:35,2021-01-01,00:19:35,CUST00006,ACC08924,MER0359,UPI,Merchant Payment,4825.91,Successful,Android,DEV00006A,Bhopal,Madhya Pradesh,192.0.2.19,WiFi,QR Code,NaN,NaN,1,2927.50,64.85,0,0,0.0,1,0,0,0,0,NaN,10,Low
1,TXN00012290,2021-01-01 00:42:02,2021-01-01,00:42:02,CUST03884,ACC09772,MER0525,UPI,Mobile Recharge,249.52,Successful,Web,DEV03884A,Nashik,Maharashtra,192.0.2.244,5G,Mobile App,NaN,NaN,1,352.77,-29.27,0,0,0.0,1,0,0,0,0,NaN,10,Low
2,TXN00048600,2021-01-01 02:54:34,2021-01-01,02:54:34,CUST03386,ACC00829,MER0398,Debit Card,Bill Payment,422.93,Successful,Android,DEV03386B,Chennai,Tamil Nadu,192.0.2.170,4G,Mobile App,NaN,NaN,1,1252.05,-66.22,0,0,0.0,1,0,0,0,0,NaN,10,Low
3,TXN00066775,2021-01-01 03:20:03,2021-01-01,03:20:03,CUST06720,ACC07958,MER0731,UPI,Bank Transfer,692.90,Successful,iOS,DEV06720A,Noida,Uttar Pradesh,192.0.2.249,Other,POS,NaN,NaN,1,337.84,105.10,0,0,0.0,1,0,0,0,0,NaN,10,Low
4,TXN00080882,2021-01-01 04:07:36,2021-01-01,04:07:36,CUST07818,ACC05000,MER0318,UPI,Bill Payment,443.27,Successful,Android,DEV07818A,Chennai,Tamil Nadu,192.0.2.79,4G,Mobile App,NaN,NaN,1,927.39,-52.20,0,0,0.0,1,0,0,0,0,NaN,10,Low

CUSTOMERS

,Customer_ID,Customer_Name,Age,Gender,City,State,Customer_Since,Customer_Segment,KYC_Status,Home_Device_ID_1,Home_Device_ID_2,Baseline_Avg_Amount
0,CUST00001,Aditya Singh,25,Male,Bhopal,Madhya Pradesh,2021-01-31,Mass Market,Verified,DEV00001A,DEV00001B,1981.34
1,CUST00002,Rahul More,50,Male,Delhi,Delhi,2024-04-17,Mass Market,Verified,DEV00002A,DEV00002B,940.88
2,CUST00003,Pooja Das,35,Male,Bengaluru,Karnataka,2020-05-31,Business,Verified,DEV00003A,DEV00003B,41899.39
3,CUST00004,Nikhil Verma,42,Male,Nashik,Maharashtra,2024-03-11,Mass Market,Verified,DEV00004A,DEV00004B,1223.27
4,CUST00005,Aditya Chavan,32,Male,Vadodara,Gujarat,2022-04-06,Mass Market,Verified,DEV00005A,DEV00005B,1240.36

In [5]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 34 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Transaction_ID                   100000 non-null  object
 1   Transaction_Timestamp            100000 non-null  object
 2   Transaction_Date                 100000 non-null  object
 3   Transaction_Time                 100000 non-null  object
 4   Customer_ID                      100000 non-null  object
 5   Account_ID                       100000 non-null  object
 6   Merchant_ID                      100000 non-null  object
 7   Payment_Method                   100000 non-null  object
 8   Transaction_Type                 100000 non-null  object
 9   Amount                           100000 non-null  float64
 10  Transaction_Status               100000 non-null  object
 11  Device_Type                      100000 non-null  object
 12  Device_ID                        100000 non-null  object
 13  Location                         100000 non-null  object
 14  State                            100000 non-null  object
 15  IP_Address                       100000 non-null  object
 16  Network_Type                     100000 non-null  object
 17  Transaction_Channel              100000 non-null  object
 18  Previous_Transaction_Time        90000 non-null   object
 19  Time_Since_Last_Transaction_Min  90000 non-null   float64
 20  Velocity_10Min_Count             100000 non-null  int64
 21  Customer_Avg_Amount              100000 non-null  float64
 22  Amount_Deviation_Pct             100000 non-null  float64
 23  New_Device_Flag                  100000 non-null  int64
 24  Location_Mismatch_Flag           100000 non-null  int64
 25  Geo_Distance_KM                  100000 non-null  float64
 26  Unusual_Hour_Flag                100000 non-null  int64
 27  IP_Mismatch_Flag                 100000 non-null  int64
 28  Failed_Burst_Flag                100000 non-null  int64
 29  Merchant_Risk_Flag               100000 non-null  int64
 30  Fraud_Flag                       100000 non-null  int64
 31  Fraud_Reason                     3000 non-null    object
 32  Risk_Score                       100000 non-null  int64
 33  Risk_Level                       100000 non-null  object
dtypes: float64(5), int64(9), object(20)
memory usage: 25.9+ MB

In [6]:
missing_tx = transactions.isnull().sum()

missing_tx[missing_tx > 0]

Previous_Transaction_Time          10000
Time_Since_Last_Transaction_Min    10000
Fraud_Reason                       97000
dtype: int64

In [7]:
print("Duplicate Rows:", transactions.duplicated().sum())
print(
    "Duplicate Transaction IDs:",
    transactions["Transaction_ID"].duplicated().sum()
)
print(
    "Duplicate Customer IDs:",
    customers["Customer_ID"].duplicated().sum()
)

Duplicate Rows: 0
Duplicate Transaction IDs: 0
Duplicate Customer IDs: 0

In [8]:
transactions["Transaction_Timestamp"] = pd.to_datetime(
    transactions["Transaction_Timestamp"]
)

transactions["Transaction_Date"] = pd.to_datetime(
    transactions["Transaction_Date"]
)

transactions["Previous_Transaction_Time"] = pd.to_datetime(
    transactions["Previous_Transaction_Time"],
    errors="coerce"
)

customers["Customer_Since"] = pd.to_datetime(
    customers["Customer_Since"]
)

In [9]:
transactions["Year"] = transactions["Transaction_Date"].dt.year
transactions["Month"] = transactions["Transaction_Date"].dt.month
transactions["Month_Name"] = transactions["Transaction_Date"].dt.month_name()
transactions["Day"] = transactions["Transaction_Date"].dt.day
transactions["Hour"] = transactions["Transaction_Timestamp"].dt.hour
transactions["Day_Name"] = transactions["Transaction_Date"].dt.day_name()

In [10]:
transactions["Amount"].describe()

count    100000.000000
mean       6360.116772
std       15814.071623
min          20.000000
25%         583.800000
50%        1651.145000
75%        5239.055000
max      500000.000000
Name: Amount, dtype: float64

In [11]:
fraud_summary = transactions.groupby("Fraud_Flag").agg(
    Transactions=("Transaction_ID", "count"),
    Total_Amount=("Amount", "sum"),
    Average_Amount=("Amount", "mean"),
    Average_Risk_Score=("Risk_Score", "mean")
).reset_index()

fraud_summary

   Fraud_Flag  Transactions  Total_Amount  Average_Amount  Average_Risk_Score
0           0         97000  5.723557e+08     5900.574118            2.530825
1           1          3000  6.365599e+07    21218.662577           18.973333

In [12]:
fraud_reason_analysis = (
    transactions[transactions["Fraud_Flag"] == 1]
    .groupby("Fraud_Reason")
    .agg(
        Fraud_Transactions=("Transaction_ID", "count"),
        Fraud_Amount=("Amount", "sum"),
        Avg_Risk_Score=("Risk_Score", "mean")
    )
    .reset_index()
    .sort_values("Fraud_Transactions", ascending=False)
)

fraud_reason_analysis

               Fraud_Reason  Fraud_Transactions  Fraud_Amount  Avg_Risk_Score
0       High Amount Anomaly                 620   45497312.24        4.903226
6           Velocity Attack                 617    7226891.84       40.931929
3                New Device                 451    2668457.15       22.771619
2         Location Mismatch                 399    2075607.28       22.456140
5              Unusual Hour                 328    2518902.80       10.060976
1               IP Mismatch                 293    1874308.02       17.969283
4  Repeated Failed Attempts                 292    1794508.40        2.842466

In [13]:
customer_analysis = (
    transactions.groupby("Customer_ID")
    .agg(
        Total_Transactions=("Transaction_ID", "count"),
        Total_Spend=("Amount", "sum"),
        Avg_Transaction=("Amount", "mean"),
        Successful_Transactions=("Transaction_Status", 
                                   lambda x: (x == "Successful").sum()),
        Failed_Transactions=("Transaction_Status",
                             lambda x: (x == "Failed").sum()),
        Fraud_Transactions=("Fraud_Flag", "sum"),
        Max_Risk_Score=("Risk_Score", "max")
    )
    .reset_index()
)

customer_analysis.head()

,Customer_ID,Total_Transactions,Total_Spend,Avg_Transaction,Successful_Transactions,Failed_Transactions,Fraud_Transactions,Max_Risk_Score
0,CUST00001,9,23324.93,2591.658889,9,0,0,10
1,CUST00002,13,6527.64,502.126154,11,0,0,10
2,CUST00003,10,414982.95,41498.295000,9,1,1,20
3,CUST00004,13,13444.48,1034.190769,13,0,0,10
4,CUST00005,12,80262.22,6688.518333,10,2,3,85

In [14]:
customer_360 = transactions.merge(
    customers,
    on="Customer_ID",
    how="left",
    validate="many_to_one"
)

print(customer_360.shape)
customer_360.head()

(100000, 51)

,Transaction_ID,Transaction_Timestamp,Transaction_Date,Transaction_Time,Customer_ID,Account_ID,Merchant_ID,Payment_Method,Transaction_Type,Amount,Transaction_Status,Device_Type,Device_ID,Location,State_x,IP_Address,Network_Type,Transaction_Channel,Previous_Transaction_Time,Time_Since_Last_Transaction_Min,Velocity_10Min_Count,Customer_Avg_Amount,Amount_Deviation_Pct,New_Device_Flag,Location_Mismatch_Flag,Geo_Distance_KM,Unusual_Hour_Flag,IP_Mismatch_Flag,Failed_Burst_Flag,Merchant_Risk_Flag,Fraud_Flag,Fraud_Reason,Risk_Score,Risk_Level,Year,Month,Month_Name,Day,Hour,Day_Name,Customer_Name,Age,Gender,City,State_y,Customer_Since,Customer_Segment,KYC_Status,Home_Device_ID_1,Home_Device_ID_2,Baseline_Avg_Amount
0,TXN00062954,2021-01-01 00:19:35,2021-01-01,00:19:35,CUST00006,ACC08924,MER0359,UPI,Merchant Payment,4825.91,Successful,Android,DEV00006A,Bhopal,Madhya Pradesh,192.0.2.19,WiFi,QR Code,NaT,NaN,1,2927.50,64.85,0,0,0.0,1,0,0,0,0,NaN,10,Low,2021,1,January,1,0,Friday,Vivaan Gupta,28,Male,Bhopal,Madhya Pradesh,2019-11-01,Affluent,Verified,DEV00006A,DEV00006B,2927.50
1,TXN00012290,2021-01-01 00:42:02,2021-01-01,00:42:02,CUST03884,ACC09772,MER0525,UPI,Mobile Recharge,249.52,Successful,Web,DEV03884A,Nashik,Maharashtra,192.0.2.244,5G,Mobile App,NaT,NaN,1,352.77,-29.27,0,0,0.0,1,0,0,0,0,NaN,10,Low,2021,1,January,1,0,Friday,Riya Singh,44,Female,Nashik,Maharashtra,2024-07-02,Student,Verified,DEV03884A,DEV03884B,352.77
2,TXN00048600,2021-01-01 02:54:34,2021-01-01,02:54:34,CUST03386,ACC00829,MER0398,Debit Card,Bill Payment,422.93,Successful,Android,DEV03386B,Chennai,Tamil Nadu,192.0.2.170,4G,Mobile App,NaT,NaN,1,1252.05,-66.22,0,0,0.0,1,0,0,0,0,NaN,10,Low,2021,1,January,1,2,Friday,Rahul Kulkarni,44,Male,Chennai,Tamil Nadu,2021-09-02,Mass Market,Verified,DEV03386A,DEV03386B,1252.05
3,TXN00066775,2021-01-01 03:20:03,2021-01-01,03:20:03,CUST06720,ACC07958,MER0731,UPI,Bank Transfer,692.90,Successful,iOS,DEV06720A,Noida,Uttar Pradesh,192.0.2.249,Other,POS,NaT,NaN,1,337.84,105.10,0,0,0.0,1,0,0,0,0,NaN,10,Low,2021,1,January,1,3,Friday,Riya Joshi,43,Male,Noida,Uttar Pradesh,2024-07-01,Student,Pending,DEV06720A,DEV06720B,337.84
4,TXN00080882,2021-01-01 04:07:36,2021-01-01,04:07:36,CUST07818,ACC05000,MER0318,UPI,Bill Payment,443.27,Successful,Android,DEV07818A,Chennai,Tamil Nadu,192.0.2.79,4G,Mobile App,NaT,NaN,1,927.39,-52.20,0,0,0.0,1,0,0,0,0,NaN,10,Low,2021,1,January,1,4,Friday,Aditya Gupta,59,Female,Chennai,Tamil Nadu,2018-07-23,Mass Market,Verified,DEV07818A,DEV07818B,927.39

In [15]:
fraud_counts = (
    transactions["Fraud_Flag"]
    .value_counts()
    .rename(index={0: "Non-Fraud", 1: "Fraud"})
)

print(fraud_counts)

Fraud_Flag
Non-Fraud    97000
Fraud         3000
Name: count, dtype: int64

In [16]:
fraud_rate = transactions["Fraud_Flag"].mean() * 100

print(f"Overall Fraud Rate: {fraud_rate:.2f}%")

Overall Fraud Rate: 3.00%

In [17]:
fraud_reason = (
    transactions[transactions["Fraud_Flag"] == 1]
    .groupby("Fraud_Reason")
    .agg(
        Fraud_Count=("Transaction_ID", "count"),
        Fraud_Amount=("Amount", "sum"),
        Avg_Risk_Score=("Risk_Score", "mean")
    )
    .sort_values("Fraud_Count", ascending=False)
    .reset_index()
)

fraud_reason

               Fraud_Reason  Fraud_Count  Fraud_Amount  Avg_Risk_Score
0       High Amount Anomaly          620   45497312.24        4.903226
1           Velocity Attack          617    7226891.84       40.931929
2                New Device          451    2668457.15       22.771619
3         Location Mismatch          399    2075607.28       22.456140
4              Unusual Hour          328    2518902.80       10.060976
5               IP Mismatch          293    1874308.02       17.969283
6  Repeated Failed Attempts          292    1794508.40        2.842466

In [18]:
behavior_columns = {
    "New Device": "New_Device_Flag",
    "Location Mismatch": "Location_Mismatch_Flag",
    "Unusual Hour": "Unusual_Hour_Flag",
    "IP Mismatch": "IP_Mismatch_Flag",
    "Failed Burst": "Failed_Burst_Flag",
    "High Velocity": "Velocity_10Min_Count"
}

behavior_summary = []

for name, column in behavior_columns.items():

    if column == "Velocity_10Min_Count":
        flagged = transactions[column] >= 3
    else:
        flagged = transactions[column] == 1

    total_flagged = flagged.sum()
    fraud_flagged = transactions.loc[flagged, "Fraud_Flag"].sum()

    fraud_rate = (
        fraud_flagged / total_flagged * 100
        if total_flagged > 0 else 0
    )

    behavior_summary.append({
        "Behavior": name,
        "Flagged_Transactions": total_flagged,
        "Fraud_Transactions": fraud_flagged,
        "Fraud_Rate_%": round(fraud_rate, 2)
    })

behavior_summary = pd.DataFrame(behavior_summary)

behavior_summary

            Behavior  Flagged_Transactions  Fraud_Transactions  Fraud_Rate_%
0         New Device                   861                 861        100.00
1  Location Mismatch                   797                 797        100.00
2       Unusual Hour                 25076                1047          4.18
3        IP Mismatch                   293                 293        100.00
4       Failed Burst                   205                 205        100.00
5      High Velocity                   205                 205        100.00

In [19]:
amount_analysis = transactions[
    ["Transaction_ID",
     "Customer_ID",
     "Amount",
     "Customer_Avg_Amount",
     "Amount_Deviation_Pct",
     "Fraud_Flag"]
].copy()

amount_analysis["Amount_vs_Baseline"] = (
    amount_analysis["Amount"] /
    amount_analysis["Customer_Avg_Amount"]
)

amount_analysis.sort_values(
    "Amount_Deviation_Pct",
    ascending=False
).head(20)

,Transaction_ID,Customer_ID,Amount,Customer_Avg_Amount,Amount_Deviation_Pct,Fraud_Flag,Amount_vs_Baseline
36573,TXN00094145,CUST07745,122505.82,212.32,57597.70,1,576.986718
22665,TXN00035148,CUST05844,129729.64,394.69,32768.87,1,328.687426
34312,TXN00057907,CUST05754,90552.27,284.55,31723.29,1,318.229731
12989,TXN00081502,CUST07702,50000.00,172.85,28826.54,1,289.268152
97246,TXN00019339,CUST01151,50000.00,173.52,28715.84,1,288.151222
8050,TXN00017423,CUST08781,50000.00,188.06,26487.77,1,265.872594
8473,TXN00065969,CUST02252,50000.00,192.81,25832.51,1,259.322649
82859,TXN00038651,CUST08776,50000.00,195.94,25417.75,1,255.180157
6206,TXN00059484,CUST07351,50000.00,215.32,23121.11,1,232.212521
25248,TXN00059637,CUST01560,50000.00,216.72,22971.06,1,230.712440
36928,TXN00010950,CUST02186,50000.00,221.57,22465.87,1,225.662319
18304,TXN00005052,CUST03419,50000.00,225.30,22092.93,1,221.926320
20519,TXN00010434,CUST03149,50000.00,229.30,21705.24,1,218.054950
22790,TXN00005098,CUST00584,50000.00,231.73,21476.50,1,215.768351
56592,TXN00036460,CUST00584,50000.00,231.73,21476.50,1,215.768351
76729,TXN00004911,CUST06907,50000.00,237.98,20910.24,1,210.101689
66775,TXN00013877,CUST07563,50000.00,238.21,20889.78,1,209.898829
35491,TXN00088439,CUST04575,50000.00,241.71,20586.30,1,206.859460
72406,TXN00011984,CUST00447,50000.00,244.20,20374.92,1,204.750205
98954,TXN00010356,CUST05738,50000.00,251.88,19751.05,1,198.507226

In [20]:
high_amount = transactions[
    transactions["Fraud_Reason"] == "High Amount Anomaly"
]

print("High Amount Fraud Transactions:", len(high_amount))
print(
    "Average Fraud Amount:",
    round(high_amount["Amount"].mean(), 2)
)
print(
    "Average Deviation %:",
    round(high_amount["Amount_Deviation_Pct"].mean(), 2)
)

High Amount Fraud Transactions: 620
Average Fraud Amount: 73382.76
Average Deviation %: 3982.54

In [21]:
customer_risk = (
    transactions.groupby("Customer_ID")
    .agg(
        Total_Transactions=("Transaction_ID", "count"),
        Total_Spend=("Amount", "sum"),
        Avg_Transaction=("Amount", "mean"),
        Fraud_Transactions=("Fraud_Flag", "sum"),
        Max_Risk_Score=("Risk_Score", "max"),
        Avg_Risk_Score=("Risk_Score", "mean")
    )
    .reset_index()
)

customer_risk.head()

,Customer_ID,Total_Transactions,Total_Spend,Avg_Transaction,Fraud_Transactions,Max_Risk_Score,Avg_Risk_Score
0,CUST00001,9,23324.93,2591.658889,0,10,2.222222
1,CUST00002,13,6527.64,502.126154,0,10,3.846154
2,CUST00003,10,414982.95,41498.295000,1,20,5.500000
3,CUST00004,13,13444.48,1034.190769,0,10,3.076923
4,CUST00005,12,80262.22,6688.518333,3,85,14.583333

In [22]:
def classify_customer_risk(score):
    if score >= 61:
        return "High"
    elif score >= 31:
        return "Medium"
    else:
        return "Low"


customer_risk["Customer_Risk_Level"] = (
    customer_risk["Max_Risk_Score"]
    .apply(classify_customer_risk)
)

customer_risk["Customer_Risk_Level"].value_counts()

Customer_Risk_Level
Low       9794
High       198
Medium       8
Name: count, dtype: int64

In [23]:
top_high_risk = (
    customer_risk[
        customer_risk["Customer_Risk_Level"] == "High"
    ]
    .sort_values(
        ["Max_Risk_Score", "Fraud_Transactions", "Total_Spend"],
        ascending=False
    )
    .head(10)
)

top_high_risk

,Customer_ID,Total_Transactions,Total_Spend,Avg_Transaction,Fraud_Transactions,Max_Risk_Score,Avg_Risk_Score,Customer_Risk_Level
1216,CUST01217,9,162965.27,18107.252222,3,95,16.111111,High
5843,CUST05844,7,132194.32,18884.902857,3,95,20.714286,High
8726,CUST08727,15,128276.15,8551.743333,3,95,12.333333,High
3187,CUST03188,13,118463.46,9112.573846,6,85,20.000000,High
7815,CUST07816,11,138914.10,12628.554545,5,85,15.000000,High
1815,CUST01816,18,1049201.54,58288.974444,4,85,10.277778,High
7745,CUST07746,14,120096.82,8578.344286,4,85,13.571429,High
973,CUST00974,12,76365.55,6363.795833,4,85,13.750000,High
7350,CUST07351,12,59400.14,4950.011667,4,85,11.250000,High
7612,CUST07613,15,56801.68,3786.778667,4,85,13.333333,High

In [24]:
monthly_fraud = (
    transactions.groupby(["Year", "Month"])
    .agg(
        Total_Transactions=("Transaction_ID", "count"),
        Fraud_Transactions=("Fraud_Flag", "sum"),
        Total_Amount=("Amount", "sum"),
        Fraud_Amount=(
            "Amount",
            lambda x: x[
                transactions.loc[x.index, "Fraud_Flag"] == 1
            ].sum()
        )
    )
    .reset_index()
)

monthly_fraud["Fraud_Rate_%"] = (
    monthly_fraud["Fraud_Transactions"] /
    monthly_fraud["Total_Transactions"] * 100
)

monthly_fraud.head(12)

,Year,Month,Total_Transactions,Fraud_Transactions,Total_Amount,Fraud_Amount,Fraud_Rate_%
0,2021,1,1706,55,10469235.21,745207.57,3.223916
1,2021,2,1462,53,9024670.44,989100.13,3.625171
2,2021,3,1669,43,9463383.84,636381.34,2.576393
3,2021,4,1557,48,10398056.00,1408253.43,3.082852
4,2021,5,1669,60,11252169.46,1361621.76,3.594967
5,2021,6,1647,44,9898422.41,825858.02,2.671524
6,2021,7,1734,45,11125208.94,780449.80,2.595156
7,2021,8,1776,55,12647976.25,1327105.13,3.096847
8,2021,9,1493,33,8740882.40,528524.41,2.210315
9,2021,10,1762,52,11074696.49,962310.16,2.951192
10,2021,11,1721,46,11099028.85,1175694.22,2.672865
11,2021,12,1772,55,10750117.69,888243.99,3.103837

In [25]:
investigation_queue = (
    transactions[
        transactions["Fraud_Flag"] == 1
    ][
        [
            "Transaction_ID",
            "Customer_ID",
            "Amount",
            "Payment_Method",
            "Location",
            "Risk_Score",
            "Risk_Level",
            "Fraud_Reason",
            "Transaction_Date",
            "Transaction_Time"
        ]
    ]
    .sort_values(
        ["Risk_Score", "Amount"],
        ascending=False
    )
)

investigation_queue.head(20)

,Transaction_ID,Customer_ID,Amount,Payment_Method,Location,Risk_Score,Risk_Level,Fraud_Reason,Transaction_Date,Transaction_Time
60748,TXN00036322,CUST01217,133995.08,UPI,Bhubaneswar,95,High,Velocity Attack,2022-01-23,03:13:42
22665,TXN00035148,CUST05844,129729.64,UPI,Mysuru,95,High,Velocity Attack,2021-10-02,19:17:52
45168,TXN00086694,CUST08727,107066.36,UPI,Nagpur,95,High,Velocity Attack,2024-10-05,12:09:22
38200,TXN00095500,CUST04818,72259.90,UPI,Visakhapatnam,85,High,Velocity Attack,2023-09-29,17:03:39
88331,TXN00049500,CUST03264,62932.25,UPI,Mumbai,85,High,Velocity Attack,2022-04-25,15:39:48
31080,TXN00091843,CUST05345,62641.77,UPI,Mysuru,85,High,Velocity Attack,2025-09-25,08:48:21
69868,TXN00052016,CUST04239,28225.40,UPI,Visakhapatnam,85,High,Velocity Attack,2024-11-08,10:19:41
66193,TXN00054034,CUST02081,16430.89,UPI,Indore,85,High,Velocity Attack,2021-03-13,04:29:35
9869,TXN00007548,CUST05570,16101.69,UPI,Aurangabad,85,High,Velocity Attack,2023-08-08,05:28:52
38410,TXN00072560,CUST03677,13399.80,UPI,Mysuru,85,High,Velocity Attack,2022-03-12,02:58:31
87206,TXN00021191,CUST02589,12822.74,UPI,Visakhapatnam,85,High,Velocity Attack,2024-05-12,02:33:55
45491,TXN00045082,CUST00974,12016.53,UPI,Ahmedabad,85,High,Velocity Attack,2023-12-25,07:54:50
56428,TXN00043272,CUST04184,10493.63,UPI,Delhi,85,High,Velocity Attack,2024-10-16,12:10:00
60051,TXN00047921,CUST09876,9963.92,UPI,Nagpur,85,High,Velocity Attack,2022-11-15,17:53:14
21790,TXN00078974,CUST09274,8878.23,UPI,Nashik,85,High,Velocity Attack,2025-11-17,17:34:01
95383,TXN00067770,CUST09953,7727.25,UPI,Coimbatore,85,High,Velocity Attack,2023-07-17,02:59:34
68812,TXN00006175,CUST09489,7622.59,UPI,Bengaluru,85,High,Velocity Attack,2022-03-15,07:07:35
47336,TXN00078140,CUST07351,5810.48,UPI,Bengaluru,85,High,Velocity Attack,2021-01-15,12:38:44
15943,TXN00033846,CUST00383,5668.61,UPI,Bhubaneswar,85,High,Velocity Attack,2021-08-23,13:53:52
34313,TXN00060530,CUST05754,5420.62,UPI,Mysuru,85,High,Velocity Attack,2023-03-04,22:43:49

In [26]:
fraud_reason.to_csv(
    "python_fraud_reason_analysis.csv",
    index=False
)

behavior_summary.to_csv(
    "python_behavior_analysis.csv",
    index=False
)

customer_risk.to_csv(
    "python_customer_risk_analysis.csv",
    index=False
)

monthly_fraud.to_csv(
    "python_monthly_fraud_analysis.csv",
    index=False
)

investigation_queue.to_csv(
    "python_investigation_queue.csv",
    index=False
)

print("All Python analysis files exported successfully.")

All Python analysis files exported successfully.